language: node_js
sudo: false
node_js:
  - 8
  - 6
  - 4
after_success: npm run coveralls
deploy:
  provider: npm
  email: "tlaziuk@gmail.com"
  api_key:
  on:
    tags: true
    repo: tlaziuk/mithril-route-render
